In [1]:
import numpy as np


In [3]:
array_1d = np.zeros(3)
print(array_1d)

[0. 0. 0.]


In [4]:
# creacion de una matriz multidimensional

array_2d = np.zeros((2,3))
print(array_2d)

[[0. 0. 0.]
 [0. 0. 0.]]


In [5]:
# matriz de ceros con tipo de datos Int 
array_2d_int = np.zeros((2, 3), dtype=int)
print(array_2d_int)

[[0 0 0]
 [0 0 0]]


In [7]:
#matrix con tipo de datos tupla y ceros
array_mix_type = np.zeros((2,2), dtype = [('x','int'), ('y','float')])
print(array_mix_type)
print(array_mix_type.dtype)

[[(0, 0.) (0, 0.)]
 [(0, 0.) (0, 0.)]]
[('x', '<i8'), ('y', '<f8')]


In [11]:
class Clase:
    def metodo(self, arg1, arg2):
        return 'metodo normal', self
    @classmethod
    def metododeclase(cls):
        return 'metodo de clase', cls
        

In [12]:
mi_clase = Clase()


In [13]:
mi_clase.metodo("a", "b")

('metodo normal', <__main__.Clase at 0x1c266b74980>)

In [15]:
mi_clase.metododeclase()


('metodo de clase', __main__.Clase)

In [16]:
data = np.zeros((2,), dtype=[("A", "i4"), ("B","f4"), ("C","a10")])


C:\Users\hp\AppData\Local\Temp\ipykernel_13212\1754801806.py:1: DeprecationWarning: Data type alias 'a' was deprecated in NumPy 2.0. Use the 'S' alias instead.
  data = np.zeros((2,), dtype=[("A", "i4"), ("B","f4"), ("C","a10")])
