In [2]:
import pandas as pd 
import numpy as np




In [14]:






class User:

    def __init__(self, user_id, username, password, failed_attempts=0, is_locked=False):

        self.user_id = user_id

        self.username = username

        self.password = password

        self.failed_attempts = failed_attempts

        self.is_locked = is_locked



    def reset_failed_attempts(self):

        self.failed_attempts = 0

        print(f"Failed attempts reset for user {self.username}.")



    def increment_failed_attempts(self):

        self.failed_attempts += 1

        print(f"Failed attempts for {self.username}: {self.failed_attempts}")

        if self.failed_attempts >= 3:

            self.lock_account()



    def lock_account(self):

        self.is_locked = True

        print(f"Account for {self.username} has been locked due to too many failed login attempts.")



class AuthenticationSystem:

    def __init__(self):

        self.users = pd.DataFrame(columns=["user_id", "username", "password", "failed_attempts_left", "is_locked"])



    def register_user(self, user_id, username, password):

        new_user = User(user_id, username, password)

        self.users = pd.concat([self.users, pd.DataFrame({

            "user_id": [user_id], 

            "username": [username], 

            "password": [password], 

            "failed_attempts_left": [3], 

            "is_locked": [False]

        })], ignore_index=True) # Add new user to DataFrame.

        print(f"User {username} registered successfully.")



    # Never alter this login function

    def login(self, username, password):

        user_row = self.users[self.users['username'].str.lower() == username.lower()]

        if user_row.empty:

            print(f"User {username} not found.")

            return



        user = User(user_row['user_id'].values[0], user_row['username'].values[0], user_row['password'].values[0], 

                    user_row['failed_attempts_left'].values[0], user_row['is_locked'].values[0])

        

        if user.is_locked:

            print(f"Account for {username} is locked. Please contact support.")

            return



        if password == password:

            user.increment_failed_attempts()

            user.reset_failed_attempts()

            self.update_user(user)

            print(f"User {username} logged in successfully.")

        else:

            user.reset_failed_attempts()

            self.update_user(user)



    def update_user(self, user):

        self.users.loc[self.users['username'] == user.username, 'failed_attempts_left'] = user.failed_attempts

        self.users.loc[self.users['username'] == user.username, 'is_locked'] = user.is_locked

        print(f"User {user.username}'s data updated.")



auth_system = AuthenticationSystem()

auth_system.register_user(1, "neena", "password123") 

auth_system.register_user(2, "helios", "mysecurepassword") 



auth_system.login("neena", "password321")  

auth_system.login("Neena", "password123")  

auth_system.login("neena", "password321")  

auth_system.login("neena", "password123")   



auth_system.login("helios", "mysecurepassword")

User neena registered successfully.
User helios registered successfully.
Failed attempts for neena: 4
Account for neena has been locked due to too many failed login attempts.
Failed attempts reset for user neena.
User neena's data updated.
User neena logged in successfully.
Account for Neena is locked. Please contact support.
Account for neena is locked. Please contact support.
Account for neena is locked. Please contact support.
Failed attempts for helios: 4
Account for helios has been locked due to too many failed login attempts.
Failed attempts reset for user helios.
User helios's data updated.
User helios logged in successfully.


In [45]:

s = pd.Series(np.random.randn(5), index =["a","b", "c","d","e"])
s

a    2.034138
b   -1.791829
c    1.407743
d   -0.073645
e    0.336417
dtype: float64

In [13]:
s.index


Index(['a', 'b', 'c', 'd', 'e'], dtype='object')

In [15]:
pd.Series(np.random.randn(5))

0   -1.695576
1    1.064686
2    0.370303
3   -0.167696
4   -0.632986
dtype: float64

In [42]:
# si se crea una serie a partir de un diccionario se tomara las key del diccionario como index de la serie y sus value como values de cada elemnto de la serie.
d = {"b":1, "a":0, "c":2}
pd.Series(d)     

b    1
a    0
c    2
dtype: int64

In [19]:
d = {"a":0.0,"b":1.0, "c":2.0}
pd.Series(d)


a    0.0
b    1.0
c    2.0
dtype: float64

In [20]:
pd.Series(d, index=["b","c", "d","a"])

b    1.0
c    2.0
d    NaN
a    0.0
dtype: float64

In [21]:
pd.Series(5.0, index=["a","b","c","d","e"])

a    5.0
b    5.0
c    5.0
d    5.0
e    5.0
dtype: float64

In [24]:
s.iloc[0]


np.float64(1.66491139410115)

In [25]:
s.iloc[:3]

a    1.664911
b    2.177641
c   -0.124960
dtype: float64

In [26]:
print(s)
print(s.median())

a    1.664911
b    2.177641
c   -0.124960
d    0.411669
e   -1.090565
dtype: float64
0.4116694859561944


In [27]:
s[s<0]

c   -0.124960
e   -1.090565
dtype: float64

In [28]:
s[s > s.median()]

a    1.664911
b    2.177641
dtype: float64

In [29]:
s.max(),s.min()

(np.float64(2.177640813776185), np.float64(-1.0905653409012421))

In [30]:
s.iloc[[4,3,1]]

e   -1.090565
d    0.411669
b    2.177641
dtype: float64

In [31]:
s.dtype


dtype('float64')

In [32]:
s.array


<NumpyExtensionArray>
[    np.float64(1.66491139410115),    np.float64(2.177640813776185),
 np.float64(-0.12495979275954865),   np.float64(0.4116694859561944),
  np.float64(-1.0905653409012421)]
Length: 5, dtype: float64

In [33]:
s.to_numpy()

array([ 1.66491139,  2.17764081, -0.12495979,  0.41166949, -1.09056534])

In [34]:
s["a"]


np.float64(1.66491139410115)

In [35]:
s["e"]

np.float64(-1.0905653409012421)

In [36]:
s["e"]=12.0


In [37]:
s

a     1.664911
b     2.177641
c    -0.124960
d     0.411669
e    12.000000
dtype: float64

In [38]:
"e" in s

True

In [39]:
"f" in s

False

In [42]:
"""s["f"] # enviara un error """
s.get("f")# no enviara un error 


In [43]:
s.get("f", np.nan) # enviara un valor por defectco en caso que el item no exist 

nan

In [55]:
s.iloc[1:] + s.iloc[:-1]

0         NaN
1   -3.459936
2   -0.537378
3    1.461788
4         NaN
Name: something, dtype: float64

In [48]:
#Series also has a name attribute
s = pd.Series (np.random.randn(5), name ="something")
s

0   -1.504485
1   -1.729968
2   -0.268689
3    0.730894
4    0.442678
Name: something, dtype: float64

In [49]:
s2 = s.rename("differents")

In [50]:
s2


0   -1.504485
1   -1.729968
2   -0.268689
3    0.730894
4    0.442678
Name: differents, dtype: float64

In [71]:
d = {
    #"one": pd.Series([1.0, 2.0, 3.0], index=["a", "b", "c"]),
     "one": pd.Series([1.0, 2.0, 3.0]),
    "two": pd.Series([1.0, 2.0, 3.0, 4.0], index=["a", "b", "c", "d"]),
}

In [72]:
df = pd.DataFrame(d)
df

one  two
0  1.0  NaN
1  2.0  NaN
2  3.0  NaN
a  NaN  1.0
b  NaN  2.0
c  NaN  3.0
d  NaN  4.0

In [62]:
pd.DataFrame(d, index=["d","b","a"])

one  two
d  NaN  4.0
b  2.0  2.0
a  1.0  1.0

In [64]:
pd.DataFrame(d, index=["d", "b", "a"], columns=["two","three"])

two three
d  4.0   NaN
b  2.0   NaN
a  1.0   NaN

In [65]:
df.index

Index(['a', 'b', 'c', 'd'], dtype='object')

In [74]:
d = {"one":[1.0, 2.0, 3.0, 4.0], "two":[5.0,4.0,3.0, 2.0, 1.0]}

In [75]:
d

{'one': [1.0, 2.0, 3.0, 4.0], 'two': [5.0, 4.0, 3.0, 2.0, 1.0]}

In [78]:
# All ndarrays must share the same length. 
#pd.DataFrame(d)# fallara 

d = {"one":[1.0, 2.0, 3.0, 4.0], "two":[4.0,3.0, 2.0, 1.0]}
pd.DataFrame(d)

one  two
0  1.0  4.0
1  2.0  3.0
2  3.0  2.0
3  4.0  1.0

In [46]:
data = np.zeros((2,), dtype=[("A", "i4"), ("B", "f4"), ("C", "S10")])
data


array([(0, 0., b''), (0, 0., b'')],
      dtype=[('A', '<i4'), ('B', '<f4'), ('C', 'S10')])

In [85]:
data[:]=[(1, 2.0, "Hello"), (2, 3.0, "World")]
data


array([(1, 2., b'Hello'), (2, 3., b'World')],
      dtype=[('A', '<i4'), ('B', '<f4'), ('C', 'S10')])

In [86]:
pd.DataFrame(data, index=["first", "second"])

A    B         C
first   1  2.0  b'Hello'
second  2  3.0  b'World'

In [87]:
pd.DataFrame(data, index=["first", "second"])

A    B         C
first   1  2.0  b'Hello'
second  2  3.0  b'World'

In [89]:
pd.DataFrame(data, columns=["C", "A","B"])

C  A    B
0  b'Hello'  1  2.0
1  b'World'  2  3.0

In [93]:
# Lista de diccionarios
data2 = [{"a":1,"b":2}, {"a":5, "b":10, "c":20}]
print(type(data2))
data2

<class 'list'>


[{'a': 1, 'b': 2}, {'a': 5, 'b': 10, 'c': 20}]

In [94]:
pd.DataFrame(data2)

a   b     c
0  1   2   NaN
1  5  10  20.0

In [95]:
pd.DataFrame(data2, index=["first", "second"])

a   b     c
first   1   2   NaN
second  5  10  20.0

In [100]:
pd.DataFrame(data2, columns=["a", "b","T"],index=["primero","segundo"])

a   b   T
primero  1   2 NaN
segundo  5  10 NaN

In [48]:
print(list("Alvaro Alarcon Zamora"))

list("ABC")


['A', 'l', 'v', 'a', 'r', 'o', ' ', 'A', 'l', 'a', 'r', 'c', 'o', 'n', ' ', 'Z', 'a', 'm', 'o', 'r', 'a']


['A', 'B', 'C']

In [103]:
ser = pd.Series(range(3), index=list("abc"), name="ser")
ser

a    0
b    1
c    2
Name: ser, dtype: int64

In [104]:
pd.DataFrame(ser)


ser
a    0
b    1
c    2

In [51]:
from collections import namedtuple

In [54]:
Point = namedtuple("Point", "x y")

In [111]:
punto_uno = Point(0,1)

In [112]:
print(type(punto_uno), punto_uno)

<class '__main__.Point'> Point(x=0, y=1)


In [52]:
Point3D = namedtuple("Point3D","x y z")

In [56]:
pd.DataFrame([Point3D(0,0,0), Point3D(0,3,5), Point(2,3)], index=list(range(3)))
#pd.DataFrame([Point3D(0,0,0), Point3D(0,3,5), Point(2,3)])

x  y    z
0  0  0  0.0
1  0  3  5.0
2  2  3  NaN

In [57]:
from dataclasses import make_dataclass

In [122]:
Point = make_dataclass("Point", [("x", int), ("y", int)])
print(type(Point), Point)

<class 'type'> <class '__main__.Point'>


In [123]:
pd.DataFrame([Point(0,0), Point(0,3), Point(2,3)])

x  y
0  0  0
1  0  3
2  2  3

In [124]:
df


one  two
0  1.0  NaN
1  2.0  NaN
2  3.0  NaN
a  NaN  1.0
b  NaN  2.0
c  NaN  3.0
d  NaN  4.0

In [125]:
df["one"]

0    1.0
1    2.0
2    3.0
a    NaN
b    NaN
c    NaN
d    NaN
Name: one, dtype: float64

In [126]:
d = {"one":[1.0, 2.0, 3.0, 4.0], "two":[4.0,3.0, 2.0, 1.0]}


In [129]:
df = pd.DataFrame(d)
df


one  two
0  1.0  4.0
1  2.0  3.0
2  3.0  2.0
3  4.0  1.0

In [136]:
df.index=["a","b","c","d"]
df

one  two
a  1.0  4.0
b  2.0  3.0
c  3.0  2.0
d  4.0  1.0

{'one': [1.0, 2.0, 3.0, 4.0], 'two': [4.0, 3.0, 2.0, 1.0]}

In [137]:
df


one  two
a  1.0  4.0
b  2.0  3.0
c  3.0  2.0
d  4.0  1.0

In [138]:
df["one"]


a    1.0
b    2.0
c    3.0
d    4.0
Name: one, dtype: float64

In [140]:
df["three"] = df["one"] * df["two"]

In [141]:
df

one  two  three
a  1.0  4.0    4.0
b  2.0  3.0    6.0
c  3.0  2.0    6.0
d  4.0  1.0    4.0

In [142]:
df["flag"] = df["one"] > 2

In [143]:
df

one  two  three   flag
a  1.0  4.0    4.0  False
b  2.0  3.0    6.0  False
c  3.0  2.0    6.0   True
d  4.0  1.0    4.0   True

In [144]:
df["foo"] = "bar"

In [145]:
df


one  two  three   flag  foo
a  1.0  4.0    4.0  False  bar
b  2.0  3.0    6.0  False  bar
c  3.0  2.0    6.0   True  bar
d  4.0  1.0    4.0   True  bar

In [148]:
df["one_trunc"] = df["one"][:2]
df


one  two  three   flag  foo  one_trunc
a  1.0  4.0    4.0  False  bar        1.0
b  2.0  3.0    6.0  False  bar        2.0
c  3.0  2.0    6.0   True  bar        NaN
d  4.0  1.0    4.0   True  bar        NaN

one  two  three   flag  foo  one_trunc
a  1.0  4.0    4.0  False  bar        1.0
b  2.0  3.0    6.0  False  bar        2.0
c  3.0  2.0    6.0   True  bar        NaN
d  4.0  1.0    4.0   True  bar        NaN

In [149]:
df.insert(1, "bar", df["one"])

In [150]:
df

one  bar  two  three   flag  foo  one_trunc
a  1.0  1.0  4.0    4.0  False  bar        1.0
b  2.0  2.0  3.0    6.0  False  bar        2.0
c  3.0  3.0  2.0    6.0   True  bar        NaN
d  4.0  4.0  1.0    4.0   True  bar        NaN

In [58]:
iris = pd.read_csv("data/iris.csv")

In [59]:
print(type(iris))
iris.head()

<class 'pandas.core.frame.DataFrame'>


Id  SepalLengthCm  SepalWidthCm  PetalLengthCm  PetalWidthCm      Species
0   1            5.1           3.5            1.4           0.2  Iris-setosa
1   2            4.9           3.0            1.4           0.2  Iris-setosa
2   3            4.7           3.2            1.3           0.2  Iris-setosa
3   4            4.6           3.1            1.5           0.2  Iris-setosa
4   5            5.0           3.6            1.4           0.2  Iris-setosa

In [156]:
iris.assign(sepal_ratio=iris["SepalWidthCm"] / iris["SepalLengthCm"]).head()

Id  SepalLengthCm  SepalWidthCm  PetalLengthCm  PetalWidthCm      Species  \
0   1            5.1           3.5            1.4           0.2  Iris-setosa   
1   2            4.9           3.0            1.4           0.2  Iris-setosa   
2   3            4.7           3.2            1.3           0.2  Iris-setosa   
3   4            4.6           3.1            1.5           0.2  Iris-setosa   
4   5            5.0           3.6            1.4           0.2  Iris-setosa   

   sepal_ratio  
0     0.686275  
1     0.612245  
2     0.680851  
3     0.673913  
4     0.720000

In [158]:
df
#df.loc["b"]

one  bar  two  three   flag  foo  one_trunc
a  1.0  1.0  4.0    4.0  False  bar        1.0
b  2.0  2.0  3.0    6.0  False  bar        2.0
c  3.0  3.0  2.0    6.0   True  bar        NaN
d  4.0  4.0  1.0    4.0   True  bar        NaN

In [160]:
serie1= df.loc["b"]
print(type(serie1))
serie1

<class 'pandas.core.series.Series'>


one            2.0
bar            2.0
two            3.0
three          6.0
flag         False
foo            bar
one_trunc      2.0
Name: b, dtype: object

In [161]:
df.iloc[2]

one           3.0
bar           3.0
two           2.0
three         6.0
flag         True
foo           bar
one_trunc     NaN
Name: c, dtype: object

In [166]:
print(np.random.randn(10, 4))
df = pd.DataFrame(np.random.randn(10, 4), columns=["A", "B", "C", "D"])
df

[[-1.38114527 -0.28463173 -0.76854201  0.29195759]
 [-1.18640273  1.17647122  0.23208445 -0.31980315]
 [ 0.64468065 -0.56262875  0.62581353  0.91121557]
 [-0.14366397  2.81777028  0.70425993  0.04067277]
 [-0.23895273 -0.2377311  -0.3991018   0.15337385]
 [ 0.57582174  0.59456074 -0.90485906 -0.46729658]
 [-0.20713667 -0.39523795  0.4134128  -1.94628187]
 [-0.29683826 -0.48122479  0.93847307  1.06566087]
 [ 2.07874604  1.05303418  0.63606293  1.23959398]
 [-0.30904551  0.37088548 -1.40286173  0.46907627]]


A         B         C         D
0  0.513121  0.546731 -1.594705 -0.254558
1 -1.263428  0.425366 -0.664871 -1.596474
2 -1.662623  0.809373 -1.239544  2.335078
3  0.255758 -1.486917 -0.201849 -0.399792
4 -0.024132 -0.847181  0.485104 -0.286318
5 -0.908483  1.401001 -0.827483 -0.807089
6 -0.140314 -0.640789 -0.770575 -0.794022
7 -0.091034 -0.298166 -1.300647  0.441214
8  1.244934 -1.296036  1.495636  0.997002
9 -0.538406 -1.228768  0.905144  0.683878

In [168]:
df2 = pd.DataFrame(np.random.randn(7, 3), columns=["A", "B","C"])
df2

A         B         C
0 -0.082597 -1.327135  1.065708
1 -0.444611  0.160339 -1.914655
2  0.525715  0.386047 -0.496997
3 -0.417283 -1.189578  0.480221
4 -0.581446 -0.670478  0.741491
5  1.169626 -1.886192  0.364049
6  0.526938 -0.082567  0.066548

In [170]:
df + df2

A         B         C   D
0  0.430524 -0.780404 -0.528997 NaN
1 -1.708039  0.585706 -2.579526 NaN
2 -1.136908  1.195420 -1.736541 NaN
3 -0.161525 -2.676495  0.278372 NaN
4 -0.605578 -1.517659  1.226595 NaN
5  0.261143 -0.485192 -0.463434 NaN
6  0.386624 -0.723356 -0.704027 NaN
7       NaN       NaN       NaN NaN
8       NaN       NaN       NaN NaN
9       NaN       NaN       NaN NaN

In [171]:
df

A         B         C         D
0  0.513121  0.546731 -1.594705 -0.254558
1 -1.263428  0.425366 -0.664871 -1.596474
2 -1.662623  0.809373 -1.239544  2.335078
3  0.255758 -1.486917 -0.201849 -0.399792
4 -0.024132 -0.847181  0.485104 -0.286318
5 -0.908483  1.401001 -0.827483 -0.807089
6 -0.140314 -0.640789 -0.770575 -0.794022
7 -0.091034 -0.298166 -1.300647  0.441214
8  1.244934 -1.296036  1.495636  0.997002
9 -0.538406 -1.228768  0.905144  0.683878

In [172]:
df.iloc[0]


A    0.513121
B    0.546731
C   -1.594705
D   -0.254558
Name: 0, dtype: float64

In [173]:
df - df.iloc[0]

A         B         C         D
0  0.000000  0.000000  0.000000  0.000000
1 -1.776548 -0.121364  0.929835 -1.341916
2 -2.175743  0.262642  0.355161  2.589637
3 -0.257362 -2.033648  1.392856 -0.145234
4 -0.537253 -1.393912  2.079809 -0.031760
5 -1.421604  0.854270  0.767222 -0.552531
6 -0.653434 -1.187520  0.824131 -0.539464
7 -0.604155 -0.844897  0.294058  0.695772
8  0.731813 -1.842767  3.090341  1.251560
9 -1.051527 -1.775499  2.499849  0.938436

In [175]:
df1 = pd.DataFrame({"a": [1,0,1], "b": [0, 1, 1]}, dtype=bool)
df1

a      b
0   True  False
1  False   True
2   True   True

In [177]:
df2= pd.DataFrame({"a":[0, 1 ,1], "b": [1, 1, 0]}, dtype=bool)
df2

a      b
0  False   True
1   True   True
2   True  False

In [178]:
df1 & df2

a      b
0  False  False
1  False   True
2   True  False

In [179]:
df2 | df1

a     b
0  True  True
1  True  True
2  True  True

In [180]:
df2 ^ df1

a      b
0   True   True
1   True  False
2  False   True

In [183]:
df.T


0         1         2         3         4         5         6  \
A  0.513121 -1.263428 -1.662623  0.255758 -0.024132 -0.908483 -0.140314   
B  0.546731  0.425366  0.809373 -1.486917 -0.847181  1.401001 -0.640789   
C -1.594705 -0.664871 -1.239544 -0.201849  0.485104 -0.827483 -0.770575   
D -0.254558 -1.596474  2.335078 -0.399792 -0.286318 -0.807089 -0.794022   

          7         8         9  
A -0.091034  1.244934 -0.538406  
B -0.298166 -1.296036 -1.228768  
C -1.300647  1.495636  0.905144  
D  0.441214  0.997002  0.683878

In [184]:
df

A         B         C         D
0  0.513121  0.546731 -1.594705 -0.254558
1 -1.263428  0.425366 -0.664871 -1.596474
2 -1.662623  0.809373 -1.239544  2.335078
3  0.255758 -1.486917 -0.201849 -0.399792
4 -0.024132 -0.847181  0.485104 -0.286318
5 -0.908483  1.401001 -0.827483 -0.807089
6 -0.140314 -0.640789 -0.770575 -0.794022
7 -0.091034 -0.298166 -1.300647  0.441214
8  1.244934 -1.296036  1.495636  0.997002
9 -0.538406 -1.228768  0.905144  0.683878

In [185]:
np.arange(7)

array([0, 1, 2, 3, 4, 5, 6])

In [186]:
ser1 = pd.Series([1, 2, 3], index=["a", "b", "c"])

In [187]:
ser2 = pd.Series([1, 3, 5], index=["b", "a", "c"])

In [188]:
ser1


a    1
b    2
c    3
dtype: int64

In [189]:
ser2

b    1
a    3
c    5
dtype: int64

In [190]:
np.remainder(ser1, ser2)

a    1
b    0
c    3
dtype: int64

In [191]:
ser3 = pd.Series([2, 4, 6], index=["b","c","d"])

In [192]:
ser3

b    2
c    4
d    6
dtype: int64

In [193]:
np.remainder(ser1, ser3)

a    NaN
b    0.0
c    3.0
d    NaN
dtype: float64

In [4]:
# crear una serie pasando una lista de values, dejando a Pandas crear un RangeIndex por defecto.

s =  pd.Series([1, 3, 5, np.nan, 6, 8])
s

0    1.0
1    3.0
2    5.0
3    NaN
4    6.0
5    8.0
dtype: float64

In [4]:
# Crear un DataFrame pasando un NumPy array con un datetime index usando date_range().

dates = pd.date_range("20130101", periods=6)
dates

DatetimeIndex(['2013-01-01', '2013-01-02', '2013-01-03', '2013-01-04',
               '2013-01-05', '2013-01-06'],
              dtype='datetime64[ns]', freq='D')

In [5]:
#print(np.random.randn(4,5))
df = pd.DataFrame(np.random.randn(6, 4), index=dates, columns=list("ABCD"))
df

A         B         C         D
2013-01-01  0.530117 -0.080421 -0.751336 -2.086108
2013-01-02 -0.734224 -1.749518 -0.362583 -0.656174
2013-01-03  0.923770 -0.739484  1.329151 -1.116321
2013-01-04  0.893984 -0.297589  0.682811  0.392264
2013-01-05  1.167470  0.279027  0.400001 -0.264152
2013-01-06 -1.517614  0.261890  1.243428 -0.298674

In [14]:
''' Crear un DataFrame pasando un diccionario de objetos donde las claves
son las etiquetas de las columnas y los valores son los valores de las columnas.
'''
df2 = pd.DataFrame(
    {
        "A": 1.0,
        "B": pd.Timestamp("20130102"),
        "C": pd.Series(1, index=list(range(4)), dtype="float32"),
        "D": np.array([3] * 4, dtype="int32"),
        "E": pd.Categorical(["test", "train", "test", "train"]),
        "F": "foo",
    }
)
df2


A          B    C  D      E    F
0  1.0 2013-01-02  1.0  3   test  foo
1  1.0 2013-01-02  1.0  3  train  foo
2  1.0 2013-01-02  1.0  3   test  foo
3  1.0 2013-01-02  1.0  3  train  foo

In [15]:
print(np.array([3] * 4, dtype="int32"))

[3 3 3 3]


In [16]:
 pd.Series(1, index=list(range(4)), dtype="float32")

0    1.0
1    1.0
2    1.0
3    1.0
dtype: float32

In [21]:
time = pd.Timestamp("20250411")
type(time)

pandas._libs.tslibs.timestamps.Timestamp

In [23]:
pd.date_range('1/1/2025', periods=5, freq='YE')

DatetimeIndex(['2025-12-31', '2026-12-31', '2027-12-31', '2028-12-31',
               '2029-12-31'],
              dtype='datetime64[ns]', freq='YE-DEC')

In [25]:
pd.date_range('1/1/2025', periods=3, freq='BYE')

DatetimeIndex(['2025-12-31', '2026-12-31', '2027-12-31'], dtype='datetime64[ns]', freq='BYE-DEC')

In [26]:
pd.date_range('1/1/2025', periods=10, freq='ms')

DatetimeIndex([       '2025-01-01 00:00:00', '2025-01-01 00:00:00.001000',
               '2025-01-01 00:00:00.002000', '2025-01-01 00:00:00.003000',
               '2025-01-01 00:00:00.004000', '2025-01-01 00:00:00.005000',
               '2025-01-01 00:00:00.006000', '2025-01-01 00:00:00.007000',
               '2025-01-01 00:00:00.008000', '2025-01-01 00:00:00.009000'],
              dtype='datetime64[ns]', freq='ms')

In [29]:
pd.date_range('1/2/2025', periods=10, freq='30s')

DatetimeIndex(['2025-01-02 00:00:00', '2025-01-02 00:00:30',
               '2025-01-02 00:01:00', '2025-01-02 00:01:30',
               '2025-01-02 00:02:00', '2025-01-02 00:02:30',
               '2025-01-02 00:03:00', '2025-01-02 00:03:30',
               '2025-01-02 00:04:00', '2025-01-02 00:04:30'],
              dtype='datetime64[ns]', freq='30s')

In [30]:
# Diferentes tipos de las columnas del DataFrame resultante.
df2.dtypes

A          float64
B    datetime64[s]
C          float32
D            int32
E         category
F           object
dtype: object

In [32]:
df2.head(2)

A          B    C  D      E    F
0  1.0 2013-01-02  1.0  3   test  foo
1  1.0 2013-01-02  1.0  3  train  foo

In [34]:
df2.tail(3)

A          B    C  D      E    F
1  1.0 2013-01-02  1.0  3  train  foo
2  1.0 2013-01-02  1.0  3   test  foo
3  1.0 2013-01-02  1.0  3  train  foo

In [35]:
df.head(4)

A         B         C         D
2013-01-01  1.003871  2.242251  1.059260 -1.915358
2013-01-02  1.561698  1.301986 -1.207242 -1.248543
2013-01-03 -0.113417  0.855904 -0.424323  0.250159
2013-01-04 -0.191567  0.003502  0.498146 -0.720043

In [36]:
df.tail(2)

A         B         C         D
2013-01-05 -1.341927  1.130965 -0.769492 -1.611691
2013-01-06  0.636965  0.236786 -0.787507  0.579887

In [37]:
df


A         B         C         D
2013-01-01  1.003871  2.242251  1.059260 -1.915358
2013-01-02  1.561698  1.301986 -1.207242 -1.248543
2013-01-03 -0.113417  0.855904 -0.424323  0.250159
2013-01-04 -0.191567  0.003502  0.498146 -0.720043
2013-01-05 -1.341927  1.130965 -0.769492 -1.611691
2013-01-06  0.636965  0.236786 -0.787507  0.579887

In [6]:
df.index

DatetimeIndex(['2013-01-01', '2013-01-02', '2013-01-03', '2013-01-04',
               '2013-01-05', '2013-01-06'],
              dtype='datetime64[ns]', freq='D')

In [39]:
df.columns

Index(['A', 'B', 'C', 'D'], dtype='object')

In [8]:
df.describe()

A         B         C         D
count  6.000000  6.000000  6.000000  6.000000
mean   0.210584 -0.387682  0.423579 -0.671528
std    1.083765  0.767767  0.843617  0.852730
min   -1.517614 -1.749518 -0.751336 -2.086108
25%   -0.418139 -0.629010 -0.171937 -1.001284
50%    0.712051 -0.189005  0.541406 -0.477424
75%    0.916323  0.176313  1.103274 -0.272783
max    1.167470  0.279027  1.329151  0.392264

In [9]:
df.T

2013-01-01  2013-01-02  2013-01-03  2013-01-04  2013-01-05  2013-01-06
A    0.530117   -0.734224    0.923770    0.893984    1.167470   -1.517614
B   -0.080421   -1.749518   -0.739484   -0.297589    0.279027    0.261890
C   -0.751336   -0.362583    1.329151    0.682811    0.400001    1.243428
D   -2.086108   -0.656174   -1.116321    0.392264   -0.264152   -0.298674

In [11]:
#Sort by axis
df.sort_index(axis=1, ascending=False)

D         C         B         A
2013-01-01 -2.086108 -0.751336 -0.080421  0.530117
2013-01-02 -0.656174 -0.362583 -1.749518 -0.734224
2013-01-03 -1.116321  1.329151 -0.739484  0.923770
2013-01-04  0.392264  0.682811 -0.297589  0.893984
2013-01-05 -0.264152  0.400001  0.279027  1.167470
2013-01-06 -0.298674  1.243428  0.261890 -1.517614

In [12]:
#Sort by values
df.sort_values(by="B")

A         B         C         D
2013-01-02 -0.734224 -1.749518 -0.362583 -0.656174
2013-01-03  0.923770 -0.739484  1.329151 -1.116321
2013-01-04  0.893984 -0.297589  0.682811  0.392264
2013-01-01  0.530117 -0.080421 -0.751336 -2.086108
2013-01-06 -1.517614  0.261890  1.243428 -0.298674
2013-01-05  1.167470  0.279027  0.400001 -0.264152

In [13]:
df.A


2013-01-01    0.530117
2013-01-02   -0.734224
2013-01-03    0.923770
2013-01-04    0.893984
2013-01-05    1.167470
2013-01-06   -1.517614
Freq: D, Name: A, dtype: float64

In [14]:
df["A"]

2013-01-01    0.530117
2013-01-02   -0.734224
2013-01-03    0.923770
2013-01-04    0.893984
2013-01-05    1.167470
2013-01-06   -1.517614
Freq: D, Name: A, dtype: float64

In [15]:
df[0:3]


A         B         C         D
2013-01-01  0.530117 -0.080421 -0.751336 -2.086108
2013-01-02 -0.734224 -1.749518 -0.362583 -0.656174
2013-01-03  0.923770 -0.739484  1.329151 -1.116321

In [16]:
df.loc[dates[0]]

A    0.530117
B   -0.080421
C   -0.751336
D   -2.086108
Name: 2013-01-01 00:00:00, dtype: float64

In [17]:
# seleccionar todas las filas (:) con etiquetas de la columna seleccionada

df.loc[:,["A", "B"]]



A         B
2013-01-01  0.530117 -0.080421
2013-01-02 -0.734224 -1.749518
2013-01-03  0.923770 -0.739484
2013-01-04  0.893984 -0.297589
2013-01-05  1.167470  0.279027
2013-01-06 -1.517614  0.261890

In [18]:
df.loc[dates[0], "A"]

np.float64(0.5301174706992625)

In [20]:
df.at[dates[0], "A"]

np.float64(0.5301174706992625)

In [21]:
df.iloc[3]

A    0.893984
B   -0.297589
C    0.682811
D    0.392264
Name: 2013-01-04 00:00:00, dtype: float64

In [22]:
df.iloc[3:5, 0:2]

A         B
2013-01-04  0.893984 -0.297589
2013-01-05  1.167470  0.279027

In [23]:
df.iloc[[1, 2, 4], [0, 2]]

A         C
2013-01-02 -0.734224 -0.362583
2013-01-03  0.923770  1.329151
2013-01-05  1.167470  0.400001

In [24]:
df.iloc[:, 1:3]

B         C
2013-01-01 -0.080421 -0.751336
2013-01-02 -1.749518 -0.362583
2013-01-03 -0.739484  1.329151
2013-01-04 -0.297589  0.682811
2013-01-05  0.279027  0.400001
2013-01-06  0.261890  1.243428

In [25]:
#boolean indexing
# Seleccionar filas donde df.A es mas grande que 0
df[df["A"] > 0]

A         B         C         D
2013-01-01  0.530117 -0.080421 -0.751336 -2.086108
2013-01-03  0.923770 -0.739484  1.329151 -1.116321
2013-01-04  0.893984 -0.297589  0.682811  0.392264
2013-01-05  1.167470  0.279027  0.400001 -0.264152

In [26]:
# seleccionar valores desde el DataFrame donde la condicion booleana se cumple
df[df > 0]

A         B         C         D
2013-01-01  0.530117       NaN       NaN       NaN
2013-01-02       NaN       NaN       NaN       NaN
2013-01-03  0.923770       NaN  1.329151       NaN
2013-01-04  0.893984       NaN  0.682811  0.392264
2013-01-05  1.167470  0.279027  0.400001       NaN
2013-01-06       NaN  0.261890  1.243428       NaN

In [28]:
# usando el metodo isin() para el filtrado.
df2 = df.copy()
df2

A         B         C         D
2013-01-01  0.530117 -0.080421 -0.751336 -2.086108
2013-01-02 -0.734224 -1.749518 -0.362583 -0.656174
2013-01-03  0.923770 -0.739484  1.329151 -1.116321
2013-01-04  0.893984 -0.297589  0.682811  0.392264
2013-01-05  1.167470  0.279027  0.400001 -0.264152
2013-01-06 -1.517614  0.261890  1.243428 -0.298674

In [30]:
df2["E"] = ["one", "one", "two", "three", "four", "three"]
df2

A         B         C         D      E
2013-01-01  0.530117 -0.080421 -0.751336 -2.086108    one
2013-01-02 -0.734224 -1.749518 -0.362583 -0.656174    one
2013-01-03  0.923770 -0.739484  1.329151 -1.116321    two
2013-01-04  0.893984 -0.297589  0.682811  0.392264  three
2013-01-05  1.167470  0.279027  0.400001 -0.264152   four
2013-01-06 -1.517614  0.261890  1.243428 -0.298674  three

In [32]:
df2[df2["E"].isin(["two", "four"])]

A         B         C         D     E
2013-01-03  0.92377 -0.739484  1.329151 -1.116321   two
2013-01-05  1.16747  0.279027  0.400001 -0.264152  four

In [36]:
s1 = pd.Series([1, 2, 3, 4, 5, 6], index=pd.date_range("20130102", periods=6))

In [37]:
s1


2013-01-02    1
2013-01-03    2
2013-01-04    3
2013-01-05    4
2013-01-06    5
2013-01-07    6
Freq: D, dtype: int64

In [38]:
df["F"] = s1
df

A         B         C         D    F
2013-01-01  0.530117 -0.080421 -0.751336 -2.086108  NaN
2013-01-02 -0.734224 -1.749518 -0.362583 -0.656174  1.0
2013-01-03  0.923770 -0.739484  1.329151 -1.116321  2.0
2013-01-04  0.893984 -0.297589  0.682811  0.392264  3.0
2013-01-05  1.167470  0.279027  0.400001 -0.264152  4.0
2013-01-06 -1.517614  0.261890  1.243428 -0.298674  5.0

In [39]:
df

A         B         C         D    F
2013-01-01  0.530117 -0.080421 -0.751336 -2.086108  NaN
2013-01-02 -0.734224 -1.749518 -0.362583 -0.656174  1.0
2013-01-03  0.923770 -0.739484  1.329151 -1.116321  2.0
2013-01-04  0.893984 -0.297589  0.682811  0.392264  3.0
2013-01-05  1.167470  0.279027  0.400001 -0.264152  4.0
2013-01-06 -1.517614  0.261890  1.243428 -0.298674  5.0

In [40]:
df.at[dates[0], "A"] = 0

In [41]:
df

A         B         C         D    F
2013-01-01  0.000000 -0.080421 -0.751336 -2.086108  NaN
2013-01-02 -0.734224 -1.749518 -0.362583 -0.656174  1.0
2013-01-03  0.923770 -0.739484  1.329151 -1.116321  2.0
2013-01-04  0.893984 -0.297589  0.682811  0.392264  3.0
2013-01-05  1.167470  0.279027  0.400001 -0.264152  4.0
2013-01-06 -1.517614  0.261890  1.243428 -0.298674  5.0

In [42]:
df.iat[0, 1] = 0

In [43]:
np.array([5] * len(df))

array([5, 5, 5, 5, 5, 5])

In [45]:
df


A         B         C         D    F
2013-01-01  0.000000  0.000000 -0.751336 -2.086108  NaN
2013-01-02 -0.734224 -1.749518 -0.362583 -0.656174  1.0
2013-01-03  0.923770 -0.739484  1.329151 -1.116321  2.0
2013-01-04  0.893984 -0.297589  0.682811  0.392264  3.0
2013-01-05  1.167470  0.279027  0.400001 -0.264152  4.0
2013-01-06 -1.517614  0.261890  1.243428 -0.298674  5.0

In [47]:
df.loc[: ,"D"] = np.array([5] * len(df))

In [48]:
df


A         B         C    D    F
2013-01-01  0.000000  0.000000 -0.751336  5.0  NaN
2013-01-02 -0.734224 -1.749518 -0.362583  5.0  1.0
2013-01-03  0.923770 -0.739484  1.329151  5.0  2.0
2013-01-04  0.893984 -0.297589  0.682811  5.0  3.0
2013-01-05  1.167470  0.279027  0.400001  5.0  4.0
2013-01-06 -1.517614  0.261890  1.243428  5.0  5.0

In [50]:
df2= df.copy()
df2

A         B         C    D    F
2013-01-01  0.000000  0.000000 -0.751336  5.0  NaN
2013-01-02 -0.734224 -1.749518 -0.362583  5.0  1.0
2013-01-03  0.923770 -0.739484  1.329151  5.0  2.0
2013-01-04  0.893984 -0.297589  0.682811  5.0  3.0
2013-01-05  1.167470  0.279027  0.400001  5.0  4.0
2013-01-06 -1.517614  0.261890  1.243428  5.0  5.0

In [51]:
df2[df2 > 0] = -df2
df2

A         B         C    D    F
2013-01-01  0.000000  0.000000 -0.751336 -5.0  NaN
2013-01-02 -0.734224 -1.749518 -0.362583 -5.0 -1.0
2013-01-03 -0.923770 -0.739484 -1.329151 -5.0 -2.0
2013-01-04 -0.893984 -0.297589 -0.682811 -5.0 -3.0
2013-01-05 -1.167470 -0.279027 -0.400001 -5.0 -4.0
2013-01-06 -1.517614 -0.261890 -1.243428 -5.0 -5.0

In [53]:
# Reindexing allows you to change/add/delete the index on a specified axis. This returns a copy of the data:
df1 = df.reindex(index=dates[0:4], columns=list(df.columns) + ["E"])
df1

A         B         C    D    F   E
2013-01-01  0.000000  0.000000 -0.751336  5.0  NaN NaN
2013-01-02 -0.734224 -1.749518 -0.362583  5.0  1.0 NaN
2013-01-03  0.923770 -0.739484  1.329151  5.0  2.0 NaN
2013-01-04  0.893984 -0.297589  0.682811  5.0  3.0 NaN

In [54]:
df1.loc[dates[0] : dates[1], "E"] = 1
df1

A         B         C    D    F    E
2013-01-01  0.000000  0.000000 -0.751336  5.0  NaN  1.0
2013-01-02 -0.734224 -1.749518 -0.362583  5.0  1.0  1.0
2013-01-03  0.923770 -0.739484  1.329151  5.0  2.0  NaN
2013-01-04  0.893984 -0.297589  0.682811  5.0  3.0  NaN

In [61]:
import random
numero = random.randrange(200)
print(type(numero))
numero

<class 'int'>


21